services:
  - type: web
    name: express-hello-world
    runtime: node
    plan: free
    buildCommand: yarn install --frozen-lockfile
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VERIFY_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        sync: false
      - key: OPENAI_MODEL
        sync: false
